server:
  port: 8082
  servlet:    context-path: /ui
    session:      cookie:        name: CLIENTSESSION
        
security:
  basic:
    enabled: false
  oauth2:    client:      client-id: cid
      client-secret: secret
      access-token-uri: http://localhost:8081/auth/oauth/token
      user-authorization-uri: http://localhost:8081/auth/oauth/authorize
    resource:      user-info-uri: http://localhost:8081/auth/rest/main/principal
      
spring:  thymeleaf:    cache: false